version: '3'
services:

  php:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
    command: php -S 0.0.0.0:80 -t /app/public_html/

  composer:
    image: composer
    volumes:
      - .:/app
    command: install
